# Generated by Django 4.2.5 on 2023-09-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="performance",
            options={"ordering": ["-show_time"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("performance", "row", "seat")},
        ),
    ]
